#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
    selected_name=$(basename "$selected" | tr . _)
    if [[ ! -d "$selected" ]] && ! tmux has-session -t="$selected_name" 3>/dev/null; then
        echo "Error: Could not find '$selected'."
        exit 1
    fi
else
    selected=$(find ~/dev -mindepth 2 -maxdepth 5 -type d \( -name node_modules -o -name .git -o -name .venv -o -name build \) -prune -o -type d -print | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# Check if the session already exists
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -s $selected_name -c $selected -d            # Create new session (detached)
    tmux new-window -t $selected_name -c $selected                # Create a second window
    tmux select-window -t $selected_name:1                        # Go back to the first window
    tmux send-keys -t $selected_name:1 "nvim ." C-m               # Run nvim in the first window
fi

if [[ -n $TMUX ]]; then
    # Inside tmux: switch to the session
    tmux switch-client -t $selected_name
else
    # Outside tmux: attach to the session
    tmux attach-session -t $selected_name
fi
