[general]
working_directory = "/Users/leo/dev"

[window]
decorations = "None"
option_as_alt = "Both"
padding = { x = 0, y = 5 }
dimensions = { columns = 200, lines = 50 }

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.primary]
background = "#000000"
foreground = "#dddddd"

[colors.normal]
black = "#000000"
red = "#bb281b"
green = "#5fc83b"
yellow = "#cdcb42"
blue = "#3471c6"
magenta = "#ba32ca"
cyan = "#5ecacb"
white = "#dddddd"

[colors.bright]
black = "#767676"
red = "#de3b2f"
green = "#78f94c"
yellow = "#fffd54"
blue = "#448df7"
magenta = "#e941f7"
cyan = "#77fbfd"
white = "#ffffff"

[bell]
duration = 0

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
