[settings]
fetch_remote_versions_cache = "7d"
fetch_remote_versions_timeout = "3s"
prefer_offline = true
auto_install = false
not_found_auto_install = false

[tools]
node = "24"
python = "3.12"
java = "temurin-25.0.2+10.0.LTS"
go = "latest"
